<?php

function products_menu() {
  return array (
    'p/%' => array (
      'page callback' => 'products_node_view',
      'page arguments' => array(1),
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,        
    ),
  );
}

function products_node_view($nid) {
	$node = node_load(array("nid" => $nid));
	if ($_GET['json']) {
		header('Content-Type: application/json; charset=utf-8');
		die(json_encode($node));
	}
	return node_view($node);
}
